# Generated by Django 3.2.9 on 2021-12-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviewvote',
            constraint=models.UniqueConstraint(fields=('user', 'review'), name='unique_review_vote'),
        ),
    ]
