# Generated by Django 3.2.9 on 2021-12-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='count_vote',
            field=models.IntegerField(default=0),
        ),
    ]
